from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class FileConverterPort(Protocol):
    def convert_to_pdf(self, source_path: str, output_dir: str | None = None) -> Path: ...
    def read_docx_text(self, path: str) -> str: ...
    def write_docx_text(self, path: str, text: str) -> Path: ...
    def read_xlsx_sheet(self, path: str, sheet_name: str | None = None) -> list[list[Any]]: ...
    def write_xlsx_sheet(
        self, path: str, rows: list[list[Any]], sheet_name: str = "Sheet1"
    ) -> Path: ...
